	create table account (
		id integer generated by default as identity (start with 1),
		username varchar(255) not null,
		password varchar(50) not null,
		primary key (id)
	);
	
	insert into account values (1, 'admin', 'admin');

	create table privilege (
		account_id integer not null,
		privilege varchar(30) not null 
	);
	
	insert into privilege values ('1', 'ROLE_ADMIN');
	
	create table address(
				id integer generated by default as identity (start with 1), 
				street_address varchar(30) not null,
				city varchar(30) not null,
				state varchar(2) not null,
				zip varchar(5) not null,
				primary key (id),
				unique (street_address, city, state, zip));

	create table pizza_size(
				id integer generated by default as identity (start with 1), 
				size_name varchar(30) not null,
				active numeric(1,0) not null,
				primary key (id),
				unique (size_name));

	create table pizza_orders(
				id integer generated by default as identity (start with 1), 
				address_id integer not null, 
				size_id integer not null, 
				status varchar(255) not null,
				primary key(id),
				constraint po_size_id foreign key (size_id) references pizza_size(id),
				constraint po_address_id foreign key (address_id) references address(id));

	--pizza3: add version to toppings 		
	create table toppings(
				id integer generated by default as identity (start with 1), 
				--version integer,
				topping_name varchar(30) not null,
				type varchar(100) not null, 
				logo LONGVARBINARY,
				active numeric(1,0) not null,
				primary key(id),
				unique (topping_name));

	-- uses keys generated for order, topping
	create table order_topping (
				order_id integer not null, 
				topping_id integer not null,
				primary key (order_id, topping_id),
				constraint ot_order_id foreign key (order_id) references pizza_orders (id),
				constraint ot_topping_id foreign key (topping_id) references toppings(id));
		
	create table pizza_sys_tab (
				id integer not null,
				current_day integer not null, 
				last_report integer not null,
				primary key(id));
		
	insert into pizza_sys_tab values (1, 1, 1);
